// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uPAlobw-jU6X3-ahUciS8g3Pmpq2ra0',
    appId: '1:937958117671:web:e37aa6e844337d8c2c9902',
    messagingSenderId: '937958117671',
    projectId: 'carrent-b23d1',
    authDomain: 'carrent-b23d1.firebaseapp.com',
    storageBucket: 'carrent-b23d1.appspot.com',
    measurementId: 'G-QDXLP09S82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKrb-t7TIVRKCUjvAz5Agsr0mgg8-OUE',
    appId: '1:937958117671:android:0bf619288cd886b82c9902',
    messagingSenderId: '937958117671',
    projectId: 'carrent-b23d1',
    storageBucket: 'carrent-b23d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajrW32sn6M2Yu_hG8UXd-CvwinG-Yh5Q',
    appId: '1:937958117671:ios:d76c83d6089a7c332c9902',
    messagingSenderId: '937958117671',
    projectId: 'carrent-b23d1',
    storageBucket: 'carrent-b23d1.appspot.com',
    iosBundleId: 'com.example.gent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajrW32sn6M2Yu_hG8UXd-CvwinG-Yh5Q',
    appId: '1:937958117671:ios:cbcb3153e78f1fc12c9902',
    messagingSenderId: '937958117671',
    projectId: 'carrent-b23d1',
    storageBucket: 'carrent-b23d1.appspot.com',
    iosBundleId: 'com.example.gent.RunnerTests',
  );
}
